<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Rakesh-Project_fa fa-bars showmenu</name>
   <tag></tag>
   <elementGuidId>1f240f08-9439-4186-a61b-f490de350ddd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='menuicon']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-bars.showmenu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b2c85829-4900-43e4-8dcc-f0b20e488d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-bars showmenu</value>
      <webElementGuid>8eebe2cb-7b80-4d35-adba-3f395eba0c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuicon&quot;)/i[@class=&quot;fa fa-bars showmenu&quot;]</value>
      <webElementGuid>9dffc8e2-8d5f-428f-8c74-a4889933283d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='menuicon']/i</value>
      <webElementGuid>4241b5e2-b597-4bfe-a280-088fb9f7b22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>bddbf88f-cbb8-4886-a794-5c9e8ff7b4be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
