<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Admin_fa fa-users</name>
   <tag></tag>
   <elementGuidId>9f37cb82-9175-4c49-b4d8-ba974853a711</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='myiconmenu']/li[12]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-users</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cad4dd5b-1855-4d96-a839-3245f54ad580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-users</value>
      <webElementGuid>59cc0c9d-f950-4cdf-87be-2aa0b1a26ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myiconmenu&quot;)/li[12]/a[1]/i[@class=&quot;fa fa-users&quot;]</value>
      <webElementGuid>67aad585-8190-4697-831b-72d90718b133</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myiconmenu']/li[12]/a/i</value>
      <webElementGuid>619e0f9e-e0f0-4ab9-8558-42063fab3e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]/a/i</value>
      <webElementGuid>d5b253c3-c7cf-4982-bdd8-cd0e7b85c130</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
