<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Admin_fa fa-bars showmenu</name>
   <tag></tag>
   <elementGuidId>67f9482c-5bae-4076-96a5-c4b12f6fc2fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='menuicon']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-bars.showmenu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2690dbfd-afbd-427e-b5e9-697ef586cfa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-bars showmenu</value>
      <webElementGuid>a581ef09-b790-4512-934e-00f5ccb43c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuicon&quot;)/i[@class=&quot;fa fa-bars showmenu&quot;]</value>
      <webElementGuid>12189167-5c65-42a1-90b0-8d3bace0aca2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='menuicon']/i</value>
      <webElementGuid>047c56a7-c6c6-40eb-810e-3232de063992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>5d62def5-4fb5-4d43-b324-b4e0b091ab9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
