<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Rakesh-Project_fa fa-bars showmenu</name>
   <tag></tag>
   <elementGuidId>84888839-a3c7-427a-b543-7f82c93e1f7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='menuicon']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-bars.showmenu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a8f37cd0-592c-4fd8-a44e-f662e37e3cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-bars showmenu</value>
      <webElementGuid>3462c971-be21-4692-a02b-f0a75a6c57e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuicon&quot;)/i[@class=&quot;fa fa-bars showmenu&quot;]</value>
      <webElementGuid>4883c4f0-3df5-4faf-a63a-1587f8180b4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='menuicon']/i</value>
      <webElementGuid>fc7bb030-f63d-497e-a1c0-6bb8ef92fced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>74a329c6-7db1-4baa-9e83-4e2fe621b311</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
