<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>e67ad67a-9a40-4d4a-90d3-d1211f640c17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/header/ul[2]/li/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a09108d6-ab17-4380-b7d5-fb94ffc0270b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://172.16.24.74:30140/logout</value>
      <webElementGuid>25da1e2c-53da-48a9-a502-aef7bf8f329f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw600 p12 animated animated-short fadeInDown</value>
      <webElementGuid>a560fe3c-fc38-48de-82ce-1773110ff33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                         
                        Logout 
                    </value>
      <webElementGuid>7737b581-a989-4796-a6dc-f7aec263f270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;navbar bg-info navbar-fixed-top&quot;]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[@class=&quot;dropdown open&quot;]/ul[@class=&quot;dropdown-menu dropdown-persist pn w250 bg-white&quot;]/li[@class=&quot;br-t of-h&quot;]/a[@class=&quot;fw600 p12 animated animated-short fadeInDown&quot;]</value>
      <webElementGuid>efe13589-4a9b-49a6-9008-658a7c1b7efe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/header/ul[2]/li/ul/li[2]/a</value>
      <webElementGuid>8f5ceeeb-a659-479e-8189-f150a8edf558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Admin'])[1]/following::a[2]</value>
      <webElementGuid>ef9ab46e-13bf-423a-9cc3-72383f5cbe5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>e6e69d40-a9be-4bed-84d4-10dd577ae97d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://172.16.24.74:30140/logout']</value>
      <webElementGuid>ccf1c0c7-db8b-4479-94c6-ec0351a7ce30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[2]/a</value>
      <webElementGuid>d3c4976b-0d27-43f6-b4f7-62d2493e6988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://172.16.24.74:30140/logout' and (text() = ' 
                         
                        Logout 
                    ' or . = ' 
                         
                        Logout 
                    ')]</value>
      <webElementGuid>5ece3ca4-84a7-4f5b-80d7-5a53dbc0216b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
