<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Virtual Machines</name>
   <tag></tag>
   <elementGuidId>9eead2da-9bee-4f39-8a1e-aed496ae0c8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/div[2]/div/div[2]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>93a2157a-c3fe-41f0-9c27-e7ae0ce4a2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://172.16.24.74:30100/index.php/v2/vm/listing</value>
      <webElementGuid>35854f59-ef9c-48d7-995d-5351920e50ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link landing_links</value>
      <webElementGuid>dcff7f2f-1365-4b09-bee3-9d3469d5ea32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>4cb05869-0fb2-4e65-ae5f-9879887604f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Virtual Machines</value>
      <webElementGuid>8535c5b5-6f33-4131-ac8e-9560357a1f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;admin-panels&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;panel  panel-primary panel-border top&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;link-wrapper col-sm-6&quot;]/a[@class=&quot;btn btn-link landing_links&quot;]</value>
      <webElementGuid>aecd9df4-e6a8-497d-b8ac-4b7c58d89f6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div[2]/div/div[2]/div[2]/a</value>
      <webElementGuid>600039b6-db25-4991-ba1e-cd63723071cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Virtual Machines')]</value>
      <webElementGuid>b793bde3-b301-4d53-827a-7b4322ceb2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/following::a[1]</value>
      <webElementGuid>a6b14d63-6de5-4e42-9177-2866afed8459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cloud'])[1]/following::a[2]</value>
      <webElementGuid>0bbf1522-40cf-4ff5-8c3d-d04afd39b1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPAM'])[1]/preceding::a[1]</value>
      <webElementGuid>ad3f842a-6793-4ac0-80dc-00089878e729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Networks'])[1]/preceding::a[1]</value>
      <webElementGuid>fe1c4043-11f4-4956-84c7-93a7abf5a2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Virtual Machines']/parent::*</value>
      <webElementGuid>1c617814-5913-40c5-bcea-bda0f6a933c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://172.16.24.74:30100/index.php/v2/vm/listing']</value>
      <webElementGuid>fa031d85-f907-4924-bebc-ef331f36dc37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/a</value>
      <webElementGuid>fcf0deb7-91ec-4ae9-a4e8-69c23040a33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://172.16.24.74:30100/index.php/v2/vm/listing' and (text() = 'Virtual Machines' or . = 'Virtual Machines')]</value>
      <webElementGuid>96dee181-0f49-4144-8398-01827f4f2e9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
