<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>bc21eab7-ad4a-4dfa-aef8-999453eb7026</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/header/ul[2]/li/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>19afd21a-27d8-46c9-a26d-258111345709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://172.16.24.74:30140/logout</value>
      <webElementGuid>a61f2797-289a-4918-851e-953d8020f2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw600 p12 animated animated-short fadeInDown</value>
      <webElementGuid>8e1005d7-e0b7-4a1a-bafb-020207c538f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                         
                        Logout 
                    </value>
      <webElementGuid>aa9db33d-9881-45d7-bee6-78b6c69b99b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;navbar bg-info navbar-fixed-top&quot;]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[@class=&quot;dropdown open&quot;]/ul[@class=&quot;dropdown-menu dropdown-persist pn w250 bg-white&quot;]/li[@class=&quot;br-t of-h&quot;]/a[@class=&quot;fw600 p12 animated animated-short fadeInDown&quot;]</value>
      <webElementGuid>9fd6cf31-3762-4389-aa02-c21b54265a85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/header/ul[2]/li/ul/li[2]/a</value>
      <webElementGuid>22e94e23-4b66-4809-98cf-6e0649a45e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Admin'])[1]/following::a[2]</value>
      <webElementGuid>936e9548-f4f5-4e51-b76f-2d775d245d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>165a5409-93fc-4270-9429-ba26d9892502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://172.16.24.74:30140/logout']</value>
      <webElementGuid>1d75024a-7c1f-4445-a6f7-309e5f226e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[2]/a</value>
      <webElementGuid>9674f096-eef0-4ee2-ad5b-fa708f471aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://172.16.24.74:30140/logout' and (text() = ' 
                         
                        Logout 
                    ' or . = ' 
                         
                        Logout 
                    ')]</value>
      <webElementGuid>4f361319-c210-4eb4-bcb9-be0e3d391405</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
